### ISSUE TITLE
{"error":"MCP error -32603: Parsing failed: Expected \"#\ 'Go\", [ \\t\\n\\r], or end of input but \"L\" found."}

### ISSUE THREAD

**Issue by yanye666** [benborla/mcp-server-mysql#26]
**Describe the bug**
{"error":"MCP error -32603: Parsing failed: Expected \"#\ 'Go\", [ \\t\\n\\r], or end of input but \"L\" found."}

**Platform**
E.g: Cursor

**MCP Configuration**
```json
{
  "mcpServers": {
    "MySQL": {
      "command": "npx",
      "args": [
        "mcprunner",
        "ALLOW_INSERT_OPERATION=false",
        "ALLOW_UPDATE_OPERATION=false",
        "ALLOW_DELETE_OPERATION=false",
        "--",
        "npx",
        "-y",
        "@benborla29/mcp-server-mysql"
      ]
    }
  }
}
```

**Screenshots**

![Image](https://github.com/user-attachments/assets/63081545-4191-4ec7-bc51-e129646c3260)

**Additional context**
{
  "sql": "SHOW TABLES LIKE '%scene%';"
}

**Comment by benborla** [comment]
Try to add this in your environment variable "ENABLE_LOGGING=false"

**Comment by yanye666** [comment]
> 尝试将其添加到您的环境变量“ENABLE_LOGGING=false”中

same problem

**Comment by yanye666** [comment]
![Image](https://github.com/user-attachments/assets/c0a2d054-5f4b-4006-8d6d-550f4fd26ba2)

**Comment by kkrrsq** [comment]
> Try to add this in your environment variable "ENABLE_LOGGING=false"

I have also encountered the same problem, adding this environment  has no effect

**Comment by kkrrsq** [comment]
> Try to add this in your environment variable "ENABLE_LOGGING=false"

It works for me. thx

**Comment by patricleehua** [comment]
i have the same problem with you.but i fixd it. if you using in cursor for windows.then you need to using "cross-env", then it will working!:

**Comment by benborla** [comment]
This should be solved by now in the current release. Thank you

**Comment by trinhdvt** [comment]
Hi there.
I’m still encountering this error when Cursor tries to execute the `SHOW TABLES FROM xxx;` query.
Any idea to fix this? 🙇 

### Error
```
[error] user-MySQL: Error calling tool 'mysql_query': MCP error -32603: Parsing failed: Expected "#", "--", "/*", ";", "GO", [ \t\n\r], or end of input but "F" found.
```

### Platform
Cursor v1.2.1

### MCP config

```json5
{
  "command": "npx",
  "args": [
    "mcprunner",
    "MYSQL_HOST=localhost",
    "MYSQL_PORT=3306",
    "MYSQL_USER=root",
    "MYSQL_PASS=",
    "MYSQL_DB=",
    "ALLOW_INSERT_OPERATION=false",
    "ALLOW_UPDATE_OPERATION=false",
    "ALLOW_DELETE_OPERATION=false",
    "MYSQL_ENABLE_LOGGING=false",
    "ENABLE_LOGGING=false",
    "--",
    "npx",
    "-y",
    "@benborla29/mcp-server-mysql"
  ]
}
```
